# Generated by Django 5.1.6 on 2025-03-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Data Science', 'Data Science'), ('Design', 'Design')], default='Programming', max_length=50),
        ),
    ]
